apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosService
metadata:
  labels:
    app.kubernetes.io/name: thanosservice
    app.kubernetes.io/instance: thanosservice-sample
    app.kubernetes.io/part-of: thanos-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: thanos-operator
  name: thanosservice-sample
spec:
  # TODO(user): Add fields here
