## Append samples of your project ##
resources:
- _v1alpha1_thanosservice.yaml
- _v1alpha1_thanosquery.yaml
- v1alpha1_thanosreceive.yaml
- v1alpha1_thanoscompact.yaml
- _v1alpha1_thanosstore.yaml
- v1alpha1_thanosgateway.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
