---
apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosReceiveHashring
metadata:
  labels:
    app.kubernetes.io/name: thanos-operator
    app.kubernetes.io/managed-by: kustomize
  name: thanosreceivehashring-sample
spec:
  replicas: 3
  storageSize: 1Gi
  objectStorageConfig:
    key: thanos.yaml
    name: thanos-objectstorage

