name: go

on:
  push:
    branches:
      - main
      - first-dev
    tags:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis) for Go
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Linting & vetting.
        env:
          GOBIN: /tmp/.bin
        run: make lint
